language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "12"
  - "10"
  - "8"
env:
  - TSVERSION=next
  - TSVERSION=latest
  - TSVERSION=3.2.1
  - TSVERSION=3.0
matrix:
  allow_failures:
    - env: TSVERSION=next
    - env: TSVERSION=3.0
before_script:
  - if [ "$TSVERSION" = 'latest' ] && [ "$TRAVIS_NODE_VERSION" = '12' ]; then TEST_COMPILED=0; else TEST_COMPILED=1; fi
  - export TEST_COMPILED
script:
  - yarn build
  - yarn lint
  - if [ "$TEST_COMPILED" -eq 1 ]; then yarn compile-tests; fi
  - yarn add -D typescript@"$TSVERSION"
  - if [ "$TEST_COMPILED" -eq 1 ]; then yarn test-compiled --ci; else yarn test --ci; fi
after_success:
  - if [ "$TEST_COMPILED" -eq 0 ]; then yarn report-coverage; fi
