language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "12"
  - "10"
  - "8"
env:
  - TSVERSION=next
  - TSVERSION=latest
  - TSVERSION=3.0
  - TSVERSION=2.0
matrix:
  allow_failures:
    - env: TSVERSION=next
    - env: TSVERSION=2.0
before_install:
before_script:
script:
  - if [ "$TSVERSION" = 'latest' ] && [ "$TRAVIS_NODE_VERSION" = '12' ]; then REPORT=1; else REPORT=0; fi
  - export REPORT
  - yarn build
  - yarn lint
  - if [ "$REPORT" -eq 0 ]; then yarn build:tests; fi
  - yarn add -D typescript@"$TSVERSION"
  - if [ "$REPORT" -eq 1 ]; then yarn test; else yarn test:compiled; fi
after_success:
  - if [ "$REPORT" -eq 1 ]; then yarn report-coverage; fi
